name: Sync Content to Database

on:
  push:
    branches: [main]
    paths:
      - 'src/content/qa/**'
      - 'src/content/config.ts'
  workflow_dispatch: # Allow manual triggering

jobs:
  sync-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for Vercel deployment
        run: |
          echo "Waiting 90 seconds for Vercel deployment to complete..."
          sleep 90

      - name: Trigger content reindex
        run: |
          echo "🔄 Starting content synchronization..."

          response=$(curl -s -w "%{http_code}" -X POST "https://www.soaale.com/api/reindex" \
            -H "Authorization: Bearer ${{ secrets.REINDEX_TOKEN }}" \
            -H "Content-Type: application/json" \
            -o response.json)

          echo "HTTP Status: $response"
          echo "Response:"
          cat response.json

          if [ "$response" -ne 200 ]; then
            echo "❌ Content sync failed with status $response"
            exit 1
          else
            echo "✅ Content sync completed successfully"
          fi

      - name: Verify sync results
        run: |
          if [ -f response.json ]; then
            processed=$(cat response.json | grep -o '"processed":[0-9]*' | cut -d':' -f2)
            errors=$(cat response.json | grep -o '"errors":[0-9]*' | cut -d':' -f2)
            total=$(cat response.json | grep -o '"total":[0-9]*' | cut -d':' -f2)

            echo "📊 Sync Summary:"
            echo "  - Total questions: $total"
            echo "  - Processed: $processed"
            echo "  - Errors: $errors"

            if [ "$errors" -gt 0 ]; then
              echo "⚠️  Some questions had errors during sync"
              echo "Check the response details above for more information"
              # Don't exit with error for now, as some errors might be acceptable
            fi
          fi

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Content synchronization failed!"
          echo "Check the logs above for details."
          echo "You may need to:"
          echo "1. Verify SITE_URL and REINDEX_TOKEN secrets are set"
          echo "2. Check that Vercel deployment completed successfully"
          echo "3. Ensure the database is accessible"